---
Name: blockextensions
After: 'framework/*','cms/*'
---
Block:
  DisabledBlocks:
    - Block
#    - DualColumnBlock
#    - SingleColumnBlock
#    - TriColumnBlock
  extensions:
    - CustomBlockPermission
#    - Versioned("Stage","Live")
Page:
  extensions:
    - BlockinPage
ContentController:
  extensions:
    - PrintBlocks