---
Name: 'blockextensions'
---
Block:
  extensions:
    - CustomBlockPermission
#    - Versioned("Stage","Live")
Page:
  extensions:
    - BlockinPage
ContentController:
  extensions:
    - PrintBlocks