---
Name: blockextensions
After: 'framework/*','cms/*'
---
Block:
  FrontendEditable: true
  DisabledBlocks:
    - Block
#    - DualColumnBlock
#    - SingleColumnBlock
#    - TriColumnBlock
  Themes:
    blackBlue:
      title: "Black Blue"
      css: "black-blue"
    brown:
      title: "Brown y'all"
      css: "brown"
  extensions:
    - Versioned("Stage","Live")
    - CustomBlockPermission
#Page:
#  extensions:
#    - BlockinPage
#ContentController:
#  extensions:
#    - PrintBlocks
