---
Name: blockextensions
After: 'framework/*','cms/*'
---
Block:
  DisabledBlocks:
    - Block
#    - DualColumnBlock
#    - SingleColumnBlock
#    - TriColumnBlock
  extensions:
    - Versioned("Stage","Live")
    - CustomBlockPermission
#Page:
#  extensions:
#    - BlockinPage
#ContentController:
#  extensions:
#    - PrintBlocks